### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by xenoncolt** [Radiicall/jellyfin-rpc#1]
HI.
I love your work.. But can you tell me how do I build exe for your `main.rs`

**Comment by Radiicall** [comment]
Hey i didnt see the issue but im guessing you got it?

**Comment by xenoncolt** [comment]
> Hey i didn't see the issue but I'm guessing you got it?

Yeah.... Thanks for the reply.. But got it... Btw can I get ur discord... for any help purpose...

**Comment by Radiicall** [comment]
Sure, its Radical#0420
