### ISSUE TITLE
Installer does not work on MacOS

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [Radiicall/jellyfin-rpc#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

When I run the cross-platform installer, it fails trying to download the application after i complete the configuration steps. From what I can tell, this seems to be because it's trying to write to a location that would be in a Linux filesystem, and not with the Apple File System. 

### Terminal output

```
Do you want to download Jellyfin-RPC? (Y/n): y

Downloading Jellyfin-RPC
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 4892k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file /usr/local/bin/jellyfin-rpc: Permission denied
  0 4892k    0 16375    0     0  16646      0  0:05:00 --:--:--  0:05:00  333k
curl: (23) Failure writing output to destination
chmod: /usr/local/bin/jellyfin-rpc: No such file or directory
```

### Jellyfin-RPC version

N/A

### What OS are you using?

MacOS Sonoma 14.3

### What version is the Jellyfin server on?

10.8.13

**Comment by Radiicall** [comment]
Execute these commands in a terminal
```
sudo mkdir /usr/local/bin
sudo chown $USER: /usr/local/bin
```
This will create the required directory and give your user ownership over that directory so that the script can run.
Re-running the installer will then download it correctly. I might put the package on brew and modify the installer to use that instead at some point

**Comment by RealHypnoticOcelot** [comment]
I actually just ended up manually downloading the version from the releases page, but this would work too! Thanks!
