### ISSUE TITLE
Hide status when media is paused

### ISSUE THREAD

**Issue by thoralmighty** [Radiicall/jellyfin-rpc#102]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

When I pause media and leave Jellyfin Media Player minimised it remains showing as my status and overriding/hiding any games I'm playing, which can sometimes lead to confusion when people are unaware I'm playing a game. 

### Describe the solution you'd like

I'd like a configuration option to hide jellyfin-rpc when media is paused (same behaviour as stopped). While we could fully stop or even close the media player each time we want to show something else, it would be more convenient to have it hide dynamically.

**Comment by Radiicall** [comment]
Working on this [here](https://github.com/Radiicall/jellyfin-rpc/tree/show_paused)
