### ISSUE TITLE
(Optionally) Print Current Media to Text File

### ISSUE THREAD

**Issue by AkikoKumagara** [Radiicall/jellyfin-rpc#106]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

Since this program already goes to the trouble of fetching media info, it might be a nice enhancement to print a text file (if enabled) containing a single line with the currently playing media, using the user's specified separator. I've attached an example of how this might look below:
![image](https://github.com/Radiicall/jellyfin-rpc/assets/15231336/4d6e1c1d-afc7-454f-98bf-ea1901d586ba)

### Describe the solution you'd like

Being a livestreamer, I'm always looking for a solution that does as many things I could use as possible. I think this feature could benefit others in a similar situation, as most other solutions for media info display currently only support software like VLC and iTunes.

### Describe alternatives you've considered

I've tried generating my own file using the winsw.out.log file, but this has a lot of issues and is a really roundabout way of solving the problem rather than coming to the source.

### Additional context

While the single line suggestion/requirement mentioned in my request keeps things a lot neater but isn't a strict requirement.

**Comment by Radiicall** [comment]
I think this might fall out of the scope of the projecg, ill think about it

**Comment by Radiicall** [comment]
Wont be implemented
