### ISSUE TITLE
Managed to get connect to discord RPC but fails to set RPC.

### ISSUE THREAD

**Issue by Radiicall** [Radiicall/jellyfin-rpc#110]
### Discussed in https://github.com/Radiicall/jellyfin-rpc/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **Central1234** April 11, 2024</sup>
Hi, just wondering if its possible to get some help. i've managed to get the script to pick up my emby server and connect to discord. but whenever i go play something i get this error:

Failed To Set Activity
Error: The Pipe is being closed. (os error 232)

then it just re attempts to connect to RPC which it does successfully in 1 try but then attempts to set the RPC again and just goes in a loop

Would love to some help!
Thanks!</div>

**Comment by Central1234** [comment]
![image_2024-04-11_210741639](https://github.com/Radiicall/jellyfin-rpc/assets/72120029/3fb7f42c-3ff3-496b-81d9-04db6aaad37c)
Here is a photo of the window

**Comment by Radiicall** [comment]
> ![image_2024-04-11_210741639](https://private-user-images.githubusercontent.com/72120029/321771943-3fb7f42c-3ff3-496b-81d9-04db6aaad37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjYzNjYsIm5iZiI6MTcxMjg2NjA2NiwicGF0aCI6Ii83MjEyMDAyOS8zMjE3NzE5NDMtM2ZiN2Y0MmMtM2ZmMy00OTZiLTgxZDktMDRkYjZhYWFkMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDIwMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMzkyOGQ3NDRlMmVkZjBmNDRhZGE5YmEwN2RjZjNmNjhkYWZmNzU3ZGUxMWIxZjhjMDFjZmMzZjFiMjMwOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xcPuFURMsNZ8lR4-Gs6t764pYBSmyb8cwOrBZJswm5A) Here is a photo of the window

What OS are you on?

**Comment by Central1234** [comment]
> > ![image_2024-04-11_210741639](https://private-user-images.githubusercontent.com/72120029/321771943-3fb7f42c-3ff3-496b-81d9-04db6aaad37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjYzNjYsIm5iZiI6MTcxMjg2NjA2NiwicGF0aCI6Ii83MjEyMDAyOS8zMjE3NzE5NDMtM2ZiN2Y0MmMtM2ZmMy00OTZiLTgxZDktMDRkYjZhYWFkMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDIwMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMzkyOGQ3NDRlMmVkZjBmNDRhZGE5YmEwN2RjZjNmNjhkYWZmNzU3ZGUxMWIxZjhjMDFjZmMzZjFiMjMwOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xcPuFURMsNZ8lR4-Gs6t764pYBSmyb8cwOrBZJswm5A) Here is a photo of the window
> 
> What OS are you on?

Windows 11 pro.

**Comment by Radiicall** [comment]
Tried on latest release?
