### ISSUE TITLE
TV Shows aren't displaying

### ISSUE THREAD

**Issue by amarevite** [Radiicall/jellyfin-rpc#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Pretty straightforward. Version `1.0.2` works as expected, but `1.0.3` does not. Literally nothing has changed between versions on my end. I tried updating the config file with the new `append_prefix` and `add_divider` options but setting both of those to true or false doesn't resolve the issue. I watched a whole episode of a show without it fixing, so I'm definitely waiting long enough for it to detect that media is playing.

### Terminal output

I don't have any logs to show (I use a custom config location so maybe that stops logs from generating at all?) but I attached screenshots of `1.0.2` and `1.0.3` side by side in the next section of this issue.

### Jellyfin-RPC version

1.0.3

### What OS are you using?

Windows 10 22H2

### What version is the Jellyfin server on?

10.8.13

### Anything else?

Screenshots of `1.0.2` and `1.0.3` side by side:
![image](https://github.com/Radiicall/jellyfin-rpc/assets/35640607/9cb71b40-fd3f-4932-80eb-9c9900f24474)
![image](https://github.com/Radiicall/jellyfin-rpc/assets/35640607/aeac1b53-3ae4-447d-adaf-293734b4c3d0)

**Comment by LeMoonStar** [comment]
I am experiencing the same issue on Fedora Linux 39, however, not only with versions `1.0.3`, but also `1.0.2` and `1.0.0` (installed via `cargo install jellyfin-rpc-cli --version [VERSION]`).
This is my first time using jellyfin-rpc and I cannot find any misconfiguration - changing the configured values results in an error, indicating that my current values are checked should be correct.

**Comment by Radiicall** [comment]
Please try with [v1.0.4](https://github.com/Radiicall/jellyfin-rpc/releases/tag/1.0.4). I found an issue in the code on 1.0.3 that should be fixed here

**Comment by Yejia995** [comment]
> Please try with [v1.0.4](https://github.com/Radiicall/jellyfin-rpc/releases/tag/1.0.4). I found an issue in the code on 1.0.3 that should be fixed here

I'm still only able to use version v1.0.2 normally on 23H2; v1.0.4 cannot detect Jellyfin's status.

**Comment by Radiicall** [comment]
What are you trying to play?

**Comment by Yejia995** [comment]
> What are you trying to play?

TV shows

**Comment by Yejia995** [comment]
Adding `"show_simple": false` to the config solves the issue, not sure why `Some(false)` is not working.

**Comment by Radiicall** [comment]
Release 1.1.0 should have fixed this bug
