### ISSUE TITLE
Series does not show up on the RPC

### ISSUE THREAD

**Issue by breadbyte** [Radiicall/jellyfin-rpc#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Movies and Music work as expected, but does not detect any type of series playing.

(Screenshot provided, first two entries are movies, and the last two entries are music, and a series is currently playing in the background.)
![image](https://github.com/Radiicall/jellyfin-rpc/assets/14045257/a92de11d-4030-4774-bbdb-c7b6ca37613e)

### Jellyfin-RPC version

jellyfin-rpc-cli 1.0.4

### What OS are you using?

Windows 11 23H2

### What version is the Jellyfin server on?

10.8.13

**Comment by Radiicall** [comment]
Look at the latest comment in #112

**Comment by breadbyte** [comment]
Adding `"show_simple": false` to the config does indeed fix the issue.
Closing as this seems to be a duplicate, then.
