### ISSUE TITLE
Remove button from rpc

### ISSUE THREAD

**Issue by betheny19** [Radiicall/jellyfin-rpc#122]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

is there a way to remove buttons ? 

### Describe the solution you'd like

a way to remove the buttons or making it optional

**Comment by Radiicall** [comment]
```json
{
    ...
    "discord": {
        "buttons": [],
    }
}
```
Buttons will disappear if you add this to your config, look at the example config in jellyfin-rpc/example.json if you're confused

**Comment by betheny19** [comment]
Worked well , Thank you
