### ISSUE TITLE
[Question] Reset image cache?

### ISSUE THREAD

**Issue by ilia-21** [Radiicall/jellyfin-rpc#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [ ] I used `--log-level=debug` when running the program

### What went wrong?

I was setting up my music library. For some time I had a bug that would show all songs with the same cover in jellyfin. Now this is fixed, but I guess jellyfin-rpc keeps it's own database of images, because in discord rpc all images are still old bugged ones. Is there a way to reset them? 

### Jellyfin-RPC version

1.1.0

### What OS are you using?

archlinux 6.9.9-arch1-1

### What version is the Jellyfin server on?

 10.9.7

**Comment by Radiicall** [comment]
Hey, if you're using imgur then you can delete the `urls.json` file in `~/.config/jellyfin-rpc/`

**Comment by ilia-21** [comment]
Hello! Really appreciate your quick response! 
Unfortunately it doesn't seem like I'm using imgur. I installed jellyfin-rpc from AUR and just added my server url and api keys to the config. There's no `urls.json`. I will try to setup imgur and see if that helps.

**Comment by Radiicall** [comment]
> Hello! Really appreciate your quick response! Unfortunately it doesn't seem like I'm using imgur. I installed jellyfin-rpc from AUR and just added my server url and api keys to the config. There's no `urls.json`. I will try to setup imgur and see if that helps.

restarted your jellyfin server? I'm not really sure what would cause this unless you maybe use Cloudflare or some other CDN

**Comment by ilia-21** [comment]
After a bit of digging I found that this is a discord cache issue. I found what link it uses to display images in rpc, followed it, and there it is, updated cover image. 
Thanks for your time and making this amazing project!
