### ISSUE TITLE
latest version no longer support emby ?

### ISSUE THREAD

**Issue by krakerz** [Radiicall/jellyfin-rpc#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [X] I used `--log-level=debug` when running the program

### What went wrong?

tried the new version, but it's auto close / crash, seems no longer works with emby i guess?
i even tried to rebuild it from source

![ShareX_cLnFh7TJdX](https://github.com/user-attachments/assets/ea33ee79-367e-4bef-a16f-2c1b2da8f554)

i guess, i'll stick the previous version

### Jellyfin-RPC version

1.2.0

### What OS are you using?

Windows 11, x64

### What version is the Jellyfin server on?

Emby 4.8.8.0

**Comment by Radiicall** [comment]
Hey, im really unfamiliar with Emby, can you add me on discord `radical.rs` because I might need to see some api responses from emby

**Comment by Radiicall** [comment]
I think i figured out your issue, 1.2.1 should have the fix

**Comment by Radiicall** [comment]
I'm closing this for now because of 1.2.1 update, if this is not solved please reopen this issue or open a new one
