### ISSUE TITLE
Support for changing activity type for diffent types of media

### ISSUE THREAD

**Issue by piplup55** [Radiicall/jellyfin-rpc#130]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

there not really a problem, just a suggestion since discord now exposes the `WATCHING`, `LISTENING TO`, `Competing in`
https://x.com/advaithj1/status/1816655583107510517

### Describe the solution you'd like

having a config option for the type of activity you want to use maybe it could be per media type, per media type would be really helpful if you use jellyfin for music aswell as media
example global:
```
  "discord": {
    "buttons": [{ }],
    "activity": "WATCHING"
  }
```
example per media:
```
    "music": {
      "display": ["album", "year"],
      "separator": "-"
       "activity": "LISTENING"
    }
```

### Describe alternatives you've considered

maybe it could be a mix of both so you have a global type that can be overwritten by something like music

**Comment by Radiicall** [comment]
I'll check the discord api and then maybe send a feature request to the discord-rich-presence library im using

**Comment by Radiicall** [comment]
I tested this locally and sent a PR to the discord-rich-presence library, its cool that they finally added this! I've gotten so many issues about it

**Comment by Radiicall** [comment]
Also i probably wont implement changing it but i will make it "Watching Jellyfin" and "Listening to Jellyfin", for books i might keep it as playing but im not sure yet

**Comment by piplup55** [comment]
> Also i probably wont implement changing it

yeah that's fair, it was just an afterthought i had when i was going to make the FR, the way you want to do it actually does make more sense

**Comment by Radiicall** [comment]
After doing some testing i think this still needs to wait, timestamps dont seem to be working, if you know of any FOSS projects that have working timestamps when showing as "Listening to", "Competing in" or "Watching" then please send me a link so i can take a look

**Comment by piplup55** [comment]
looks like it's bugged timestamps get ignored when setting the type to listening or watching

**Comment by Radiicall** [comment]
https://github.com/vionya/discord-rich-presence/pull/40 here's the PR i submitted to upstream and it has some example images

**Comment by Radiicall** [comment]
I made a test version of jellyfin-rpc with this feature [here](https://github.com/Radiicall/jellyfin-rpc/actions/runs/10161878183)

**Comment by XDark187** [comment]
I've been using [Vencord](https://vencord.dev/) for a while with this [plugin](https://github.com/nyakowint/replaceActivityTypes/blob/main/ReplaceSettings.tsx) that allows replacing the activity with watching/streaming/competing etc.

Timestamps seems to be an issue with discord as the author of the plugin stated:

> "ActivityTypes other than Playing will only show timestamps on mobile. It's a Discord issue."

The plugin has a cool toggle where you can swap presence name and details so it shows as "watching {movie name}" instead of "watching jellyfin". having an option to toggle this would be cool too.

![image](https://github.com/user-attachments/assets/4c34c0d9-9d1e-418e-a297-0a3eb52672c4)

**Comment by Radiicall** [comment]
I dont think swapping those two is something you can do through normal means, let me know if another project is doing that without modifying the client though and ill take a look at it

**Comment by Radiicall** [comment]
my fork got merged into https://github.com/vionya/discord-rich-presence, now all we need is for discord to make timestamps work again

**Comment by Radiicall** [comment]
Timestamps are sorta working but just the wrong way thanks to a discord update.. I hope they fix it and doesnt make the new way of not being able to specify start or end time permanent

**Comment by piplup55** [comment]
it seems like discord has fixed the time bar this was added at the same time but was bugged i wonder if this could be used for movies?
![image](https://github.com/user-attachments/assets/08a39108-8efe-490c-8880-e431f14c6c39)
i tested it on the youtube music app and it seems to work, it's not as good as timestamps but it might be something you can use
![image](https://github.com/user-attachments/assets/d1a1a3d5-7769-4955-be87-446583afaa4d)

**Comment by BobbyWibowo** [comment]
I wonder if #136 will just work with that out of the box by any chance, if assuming they don't actually require new field types

**Comment by piplup55** [comment]
> I wonder if #136 will just work with that out of the box by any chance, if assuming they don't actually require new field types

i already checked it doesn't

**Comment by Radiicall** [comment]
https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-timestamps it looks like having the bar there can be done

**Comment by Radiicall** [comment]
![image](https://github.com/user-attachments/assets/f9113bba-fa3f-4153-b44e-33e4ef2bd9ec)
👀

**Comment by BobbyWibowo** [comment]
ended up building from git, it looks wonderful, thanksies
