### ISSUE TITLE
Live TV not showing on v1.1.0+ 

### ISSUE THREAD

**Issue by piplup55** [Radiicall/jellyfin-rpc#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [X] I used `--log-level=debug` when running the program

### What went wrong?

Live TV doesn't show up after updating to above 1.1.0

### Terminal output

[jellyfin-1.1.0.log](https://github.com/user-attachments/files/16417477/jellyfin-1.1.log)
[jellyfin-1.2.1.log](https://github.com/user-attachments/files/16417481/jellyfin-1.2.1.log)

### Jellyfin-RPC version

1.1.0/1.2.1

### What OS are you using?

Fedora 39

### What version is the Jellyfin server on?

10.9.8

### Anything else?

1.1.0:
![image](https://github.com/user-attachments/assets/30c4ee7f-fc02-4c11-8ae2-b775b669a9df)
1.2.1:
![image](https://github.com/user-attachments/assets/8f506433-1e2e-4ebd-af62-0341abe7b922)

**Comment by Radiicall** [comment]
Ah yes i can see the issue here, ill get it fixed

**Comment by Radiicall** [comment]
Please test the artifact at the bottom of [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/10150838318?pr=133)

**Comment by piplup55** [comment]
can confirm it works on the pr build
![image](https://github.com/user-attachments/assets/bf2f9b2a-36f1-4c1a-8be8-5bb314497c25)
