### ISSUE TITLE
Blacklisted libraries not working as intended

### ISSUE THREAD

**Issue by piplup55** [Radiicall/jellyfin-rpc#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [X] I used `--log-level=debug` when running the program

### What went wrong?

I blacklisted one of my libraries and it still shows on the RPC after 1.1.0

### Terminal output

1.1.0:
[jellyfin-1.1.log](https://github.com/user-attachments/files/16417706/hidden-jellyfin-1.1.log)
1.2.1:
[jellyfin-1.2.1.log](https://github.com/user-attachments/files/16417702/hidden-jellyfin-1.2.1.log)

### Jellyfin-RPC version

1.1.0/1.2.1

### What OS are you using?

Fedora 39

### What version is the Jellyfin server on?

10.9.8

### Anything else?

1.1.0:
![image](https://github.com/user-attachments/assets/37d5beaa-7494-4640-8f4c-e3d98168827b)
1.2.1:
![image](https://github.com/user-attachments/assets/f2d0e71c-f91b-4ca0-b307-15be9cd1ae3e)

this may also affect media types

**Comment by Radiicall** [comment]
Hey, this does not seem to be running using --log-level=debug, do you have the RUST_LOG environment variable set?

**Comment by piplup55** [comment]
my bad those logs were from a previous attempt
[1.1.0.log](https://github.com/user-attachments/files/16419458/1.1.0.log)
[1.2.1.log](https://github.com/user-attachments/files/16419459/1.2.1.log)

**Comment by Radiicall** [comment]
I found the issue here too, ill double check that its working and same with media_types

**Comment by Radiicall** [comment]
yep it works now, i have noticed something off about how the client handles blacklists as well here

**Comment by Radiicall** [comment]
You can download the artifact [here](https://github.com/Radiicall/jellyfin-rpc/actions/runs/10159193681), it has the fix for both live tv and blacklists

**Comment by piplup55** [comment]
can confirm it works on my end, thanks for the fast fixes
