### ISSUE TITLE
Suddenly no Rich Presence display from Jellyfin Media Player source

### ISSUE THREAD

**Issue by AkikoKumagara** [Radiicall/jellyfin-rpc#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [X] I used `--log-level=debug` when running the program

### What went wrong?

I don't think any changes on my end caused this, but I'm not certain...

RPC is no longer grabbing my activity from Jellyfin Media Player (which is connected directly to server using local IP) but works perfectly from a web browser running Jellyfin from the IP address.

I've attached screenshots of the terminal below showing both Media Player session (left) and a working browser session (right) with debug logging.

As always, I'm prepared to provide any further information as needed. Thanks.

### Terminal output

![image](https://github.com/user-attachments/assets/06af8574-366a-42be-a681-f45be59a42dd)
![image](https://github.com/user-attachments/assets/743814df-e344-4633-b97b-5521d41726bc)

### Jellyfin-RPC version

1.2.2

### What OS are you using?

Windows 10

### What version is the Jellyfin server on?

10.9.5

**Comment by Radiicall** [comment]
I have seen some people posting about similar issues before and i dont know what the cause could be, if its still happening then try checking jellyfin.example.com/Sessions?api_key=your_api_key while having JMP open, you should see a session in there for it and when you try playing something there should be a NowPlayingItem in there that has the information about whats playing

**Comment by AkikoKumagara** [comment]
> I have seen some people posting about similar issues before and i dont know what the cause could be, if its still happening then try checking jellyfin.example.com/Sessions?api_key=your_api_key while having JMP open, you should see a session in there for it and when you try playing something there should be a NowPlayingItem in there that has the information about whats playing

No such NowPlayingItem entry it seems... interesting. There's also no media info I can see anywhere else here.
![image](https://github.com/user-attachments/assets/78da24ee-72db-482d-849e-3413ab9ed37b)

**Comment by AkikoKumagara** [comment]
Playing from web, however, I have the expected entries. So this may be a JMP issue?

**Comment by Radiicall** [comment]
> Playing from web, however, I have the expected entries. So this may be a JMP issue?

I have no idea what causes it and there is sadly nothing i can do to fix it, its related to the server or client.. Some people have this issue and others dont, i never see this myself for instance

**Comment by AkikoKumagara** [comment]
I'm not sure. It seems intermittent and it's working again right now, but yeah, seems to be *not* an issue with your software. Thanks.

**Comment by AkikoKumagara** [comment]
Updated to the new release and it's happening again. Wish I had some idea what causes this lol.
