### ISSUE TITLE
Time remaining went from a count down on the time remaining to just showing a Controller icon and stuck at 0:00

### ISSUE THREAD

**Issue by Cracked-Fisko** [Radiicall/jellyfin-rpc#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [ ] I used `--log-level=debug` when running the program

### What went wrong?

Time remaining went from a count down on the time remaining to just showing a Controller icon and stuck at 0:00 and i cant see anything wrong with the Config json.
{
  "jellyfin": {
    "url": "http://192.168.0.135:8096",
    "api_key": "",
    "username": [
      ""
    ],
    "music": null,
    "movies": null,
    "blacklist": null,
    "self_signed_cert": null,
    "show_simple": true,
    "append_prefix": true,
    "add_divider": true
  },
  "discord": {
    "application_id": "",
    "show_paused": true,
    "buttons": [
      {
          "name": "dynamic",
          "url": "dynamic"
      },
      {
          "name": "dynamic",
          "url": "dynamic"
      }
  ]
},
  "imgur": {
    "client_id": ""
  },
  "images": {
    "enable_images": true,
    "imgur_images": true
  }
}

### Jellyfin-RPC version

1.2.2 (the latest version from 2 weeks ago)

### What OS are you using?

Windows server

### What version is the Jellyfin server on?

10.9.8

### Anything else?

![image](https://github.com/user-attachments/assets/fc2c24f5-ba13-40c6-a8d2-6797dabc93b5)
Here it should say 2hours and so remaining.

**Comment by Radiicall** [comment]
huh this is interesting, do you have an Xbox account or PlayStation account connected to discord or something? I have never seen this before.

**Comment by Cracked-Fisko** [comment]
yes a xbox account tied to my discord

**Comment by Cracked-Fisko** [comment]
but odd thing was at first it was showing correctly

**Comment by Cracked-Fisko** [comment]
only 12 hours later its now appearing like this

**Comment by Cracked-Fisko** [comment]
![image](https://github.com/user-attachments/assets/1feb49fd-7edc-482b-bf01-576c842388b9)

**Comment by Cracked-Fisko** [comment]
My Gaming RIG Client
![image](https://github.com/user-attachments/assets/fe6c2955-b745-41ce-a65f-6af05b695893)

**Comment by Cracked-Fisko** [comment]
also it would be nice if you could give the user the ability to edit this or remove the version Number, as it would neaten it up on the discord sides of things :D
![image](https://github.com/user-attachments/assets/6f26fc57-be17-42a5-8845-c587c2a273d7)

**Comment by Radiicall** [comment]
> yes a xbox & steam account tied to my discord

Do you have a game open on an Xbox with the same account? This is really the only thing i can think of

**Comment by Cracked-Fisko** [comment]
erm the acc i have connected to my Discord for xbox i don't sign in to regularly as its a test acc designed to be banned xD.
I Closed All program's that possibly could be affecting it, i even closed xbox via gaming services. still the same result
![image](https://github.com/user-attachments/assets/1f4ca602-c0ef-42d9-a333-a50b59901236)

**Comment by Cracked-Fisko** [comment]
Strange Apon closing the game it done this
![image](https://github.com/user-attachments/assets/c3b62c74-2d41-479a-ba8f-e697b6693834)
LooL - i may get banned from discord xD
![image](https://github.com/user-attachments/assets/a8a178af-7bf8-45e8-9b53-1083e3497a85)
turns out doing what I'm doing is what causing the issue, its deffo tied to Discord pulling game data that's causing this

**Comment by Cracked-Fisko** [comment]
FYI Disconnected my steam no hope still the same

**Comment by Radiicall** [comment]
Well i dont think i can help, since its happening to other rich presences as well its not tied to Jellyfin-RPC. It might be one of discords slow rollout features that will hit everyone eventually, if thats the case then i wont know how to test this until it hits me

**Comment by Radiicall** [comment]
You might see some different results with a version of jellyfin-rpc from the bottom of [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/10161912083)

**Comment by Cracked-Fisko** [comment]
Ill try 1.2.3 then

**Comment by Cracked-Fisko** [comment]
Still the same 
![image](https://github.com/user-attachments/assets/d1ed5297-ab18-45a7-9747-b37febcf97d3)

**Comment by Cracked-Fisko** [comment]
also this is paused atm

**Comment by Radiicall** [comment]
> Still the same - also this is paused atm ![image](https://private-user-images.githubusercontent.com/168500624/358395540-d1ed5297-ab18-45a7-9747-b37febcf97d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTYzNDIsIm5iZiI6MTcyMzc1NjA0MiwicGF0aCI6Ii8xNjg1MDA2MjQvMzU4Mzk1NTQwLWQxZWQ1Mjk3LWFiMTgtNDVhNy05NzQ3LWIzN2ZlYmNmOTdkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWI1YTNmMWIxYzQxNTliYjkzNjcyZWFhMmNjMjU2MWYxYzRlMzFiODU3NDUxOTc5ODAwNWQ5NWVkMmEyZTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pdpW-9fMEsqv9ZwO0RFx3w1nOTLjMpfwuEX2VVgtKLc)

huh it looks like discord is making more changes to how activities are handled, maybe clients cant set a timestamp in the future.. We just have to wait and see

**Comment by Cracked-Fisko** [comment]
strange tho as last night i was watching jellyfin and was curious, my gaming rig was off just my server was on and this is a screenshot from android, so who knows. they are deffo making updates but it think this is tied to how they are going to be also pulling activity data from a users steam acc now, on top of also what application they are running.
![image](https://github.com/user-attachments/assets/25f1e8ca-69e3-4755-b472-e74548d8741a)

**Comment by Cracked-Fisko** [comment]
Discord is seeming to become very intrusive.

**Comment by piplup55** [comment]
discord's recent games feature is the cause of this, i assume they remove the ability to add timestamps altho it doesn't stay at 0:00 for me
before:
![image](https://github.com/user-attachments/assets/3fd13062-6679-4c44-92e2-f7ebe3c30b94)
after:
![image](https://github.com/user-attachments/assets/b02fa4a4-6f03-4930-9298-c77f6a54f438)

**Comment by Radiicall** [comment]
Same thing has happened to me now...

**Comment by BobbyWibowo** [comment]
oh dang, it was already slow-rolling for y'all since last month

i only got it myself within the past few days, and stumbled upon this issue whilst intending to ask around
