### ISSUE TITLE
Request for it to use Client Secret instead of a IPC Hook.

### ISSUE THREAD

**Issue by Cracked-Fisko** [Radiicall/jellyfin-rpc#140]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

it would be good due to removing the requirement for a discord client. 

### Describe the solution you'd like

Request for it to user Client Secret instead of requiring a Hook into a discord client thus not requiring to run your discord twice on 2 machines. 

### Describe alternatives you've considered

I was looking at the Rust Code, but don't understand Rust too well. but it shouldn't be too hard to do

**Comment by Cracked-Fisko** [comment]
Yeah sadly this isn't possible to do, my bad for not looking into the discord API too tough, tho thanks for the great tool. I don't know how to close this if you could please do. as you can not do this ATM :/

**Comment by Radiicall** [comment]
yeah.. this would be great if possible, removing discord as a dependency has been a big want from me for a long time..

**Comment by Cracked-Fisko** [comment]
yeah its a shame they don't give a user the option to legally obtain a cookie and do it that way :/ 
its trash, tho as it wouldn't be too hard for them to implement on the back end.
