### ISSUE TITLE
Trying to remove one button from the RPC removes them all

### ISSUE THREAD

**Issue by lostttt1** [Radiicall/jellyfin-rpc#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [X] I used `--log-level=debug` when running the program

### What went wrong?

I want to remove one of these buttons, specifically "Shoko Episode" As it leads to a web-ui that is locally hosted so its totally useless to have it display on my profile
![image](https://github.com/user-attachments/assets/68a6fab1-183b-40f7-b0de-eec8e58537d4)
![image](https://github.com/user-attachments/assets/3e1c6130-6450-4639-a28c-92d1d132984d)

so I decided to set my config to this to hopefully include only the first button (anidb) and omit the other button, Shoko.

```
"buttons": [
      {
        "name": "dynamic",
        "url": "dynamic"
      }
    ],
```

Having one dynamic button in the json config lead to no buttons being displayed instead of only the first button.
How do I remove "Shoko Episode" in the config?

### Jellyfin-RPC version

v1.2.2

### What OS are you using?

Windows 11

### What version is the Jellyfin server on?

10.9.9

**Comment by Radiicall** [comment]
I'll have to look into this as i see nothing obviously wrong with the code.. I'll probably also add a check for localhost URLs because even trying to display those is pointless

**Comment by Radiicall** [comment]
I found a few issues in the code now that i'll get fixed in the next release
