### ISSUE TITLE
Integration with multiple users / app auth

### ISSUE THREAD

**Issue by ohitstom** [Radiicall/jellyfin-rpc#15]
So i dont entirely understand discord rpc, but would it not be possible to allow users to integrate this like so:
![image](https://user-images.githubusercontent.com/22730962/226142855-2067a400-f9b1-4639-91bf-f979fb9dcc85.png)

Then it could be used with multiple users and without the need for any single user to be logged into discord on the server for this to work?

I understand this probably isnt easy to achieve or might not even be possible but would be super cool

**Comment by Radiicall** [comment]
I'm not exactly sure what you mean by this?

**Comment by ohitstom** [comment]
nevermind this doesnt make sense.
