### ISSUE TITLE
images incorrect behavour

### ISSUE THREAD

**Issue by piplup55** [Radiicall/jellyfin-rpc#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you ran the program with debug logging?

- [X] I used `--log-level=debug` when running the program

### What went wrong?

enabling "imgur_image" without enabling "enable_images" causes the rpc to still show the album cover (the image was taken by one of my friends)
![image](https://github.com/user-attachments/assets/18c36bd6-0744-40ab-b9f7-39c50b633e83)

### Terminal output

[jellyfin-rpc.log](https://github.com/user-attachments/files/16851043/jellyfin-rpc.log)

### Jellyfin-RPC version

1.2.2

### What OS are you using?

Fedora/Arch Linux

### What version is the Jellyfin server on?

10.9.8

### Anything else?

according to the [wiki](https://github.com/Radiicall/jellyfin-rpc/wiki/Images#imgur-images)
imgur_images needs a client id and "enable_images" yet it works fine without a client id or enable_images
![image](https://github.com/user-attachments/assets/7359c1b2-c577-4517-b84b-33645d4dd655)

**Comment by Radiicall** [comment]
Without a client ID? It must be falling back to using images from jellyfin itself which is not correct.. The other problem is probably just a minor mistake in code somewhere

**Comment by Radiicall** [comment]
> Without a client ID? It must be falling back to using images from jellyfin itself which is not correct.. The other problem is probably just a minor mistake in code somewhere

Actually, do you have a urls.json (check `~/.config/jellyfin-rpc`) that it could be pulling the URLs from? It should be able to read that but it wont be able to upload new images without a client ID

**Comment by piplup55** [comment]
urls.json was empty and now it has some urls like the one i showed in the issue, i'm unsure where it's pulling it from

**Comment by Radiicall** [comment]
what? That should be impossible

**Comment by piplup55** [comment]
well i have two files one called urls.json and one called urls.json.bck which is a backup i made but it shouldn't pull any data from that afaik

**Comment by piplup55** [comment]
i figured i should make a video of the urls being added https://youtu.be/x98lD_05Oow i'm logged into imgur but i haven't given it my client id yet
note: the red marker on the side next to the line number means the file has been modified

**Comment by Radiicall** [comment]
Is the imgur url correct? Does it give you the correct image when you open it?

**Comment by piplup55** [comment]
yep the imgur url is correct and it shows in discord, it's doesn't do it for every album i assume it's caching something
![image](https://github.com/user-attachments/assets/a5510122-a610-4613-8132-8079dca50d69)
![image](https://github.com/user-attachments/assets/a2cb6a8a-0ce8-4055-bc50-30b1a63c098a)
