### ISSUE TITLE
Allow changing the name in discord

### ISSUE THREAD

**Issue by cracktorio** [Radiicall/jellyfin-rpc#158]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

Shows as "Listening to Jellyfin", providing no info except i'm using jellyfin

### Describe the solution you'd like

allow editing the "name" of the application, so that for example: when listening to Showtime by Embark Studios, it will show as "Listening to Embark Studios". Or when watching john wick, it will show as "Watching John Wick".

**Comment by Radiicall** [comment]
This is not possible without a custom client, application name is tied to application ID, a new one would have to be made for every show, artist, movie or whatever else.
