### ISSUE TITLE
Allow use without jellyfin api key

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Radiicall/jellyfin-rpc#159]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

The project is good but only issue I found is I need jellyfin api key to use, what if users of my server want to use this app but I dont wan't to give them my api key so they don't do bad things to server

### Describe the solution you'd like

Allow use of bot without api key, by login with username/password or something else

**Comment by Radiicall** [comment]
There is a way for token authentication, i made it work before.. I might do something with that to make this possible

**Comment by EsmailELBoBDev2** [comment]
> There is a way for token authentication, i made it work before.. I might do something with that to make this possible

Maybe username/password login or that would not really work?

**Comment by Radiicall** [comment]
> > There is a way for token authentication, i made it work before.. I might do something with that to make this possible
> 
> Maybe username/password login or that would not really work?

Ah you misunderstand, username/password is auth token based, the app gives creds to the server and a token is returned that can be used to authenticate actions like getting active sessions, etc.

**Comment by EsmailELBoBDev2** [comment]
> > > There is a way for token authentication, i made it work before.. I might do something with that to make this possible
> > 
> > 
> > Maybe username/password login or that would not really work?
> 
> Ah you misunderstand, username/password is auth token based, the app gives creds to the server and a token is returned that can be used to authenticate actions like getting active sessions, etc.

oh gotcha. well if there anything i can help with to make this feature alive (i'm bad at coding lol)

**Comment by Radiicall** [comment]
This feels like something that should be done with a gui of some sort, jellyfin-rpc is technically a library now so it shouldnt be that hard to make a gui frontend for it

**Comment by EsmailELBoBDev2** [comment]
Yes but I feel login options are related to core part

**Comment by kemuriXD** [comment]
@EsmailELBoBDev2
Users can get their API key from devtools when they login to their JF server. That's how I got my RPC working at least. Hope it helps you.
![chrome_Lzp6LtOx1G](https://github.com/user-attachments/assets/e6a58165-d798-49aa-bbd6-00d776fc6388)

**Comment by Radiicall** [comment]
> @EsmailELBoBDev2
> Users can get their API key from devtools when they login to their JF server. That's how I got my RPC working at least. Hope it helps you.
> ![chrome_Lzp6LtOx1G](https://github.com/user-attachments/assets/e6a58165-d798-49aa-bbd6-00d776fc6388)
> 

Cool trick! Thanks for sharing

**Comment by EsmailELBoBDev2** [comment]
> @EsmailELBoBDev2 Users can get their API key from devtools when they login to their JF server. That's how I got my RPC working at least. Hope it helps you. ![chrome_Lzp6LtOx1G](https://private-user-images.githubusercontent.com/60441676/380451252-e6a58165-d798-49aa-bbd6-00d776fc6388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5OTgyMjYsIm5iZiI6MTcyOTk5NzkyNiwicGF0aCI6Ii82MDQ0MTY3Ni8zODA0NTEyNTItZTZhNTgxNjUtZDc5OC00OWFhLWJiZDYtMDBkNzc2ZmM2Mzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDAyNTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMDdmNTFiMTczYzVkNGFiM2NlNzZhNWM4NTM2MDMzMGM2OGEyMTRmZDExZmM2OWNmMTczMDliOGE4YzcwODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kTEAvStRMJccr5t4xLX5pS8js52zKlUHNHzoxEdnFjI)

oh I thought API keys are only for admins, sorry for misunderstanding :sweat_smile: and thanks for the tip!
