### ISSUE TITLE
ActivityType as "Watching" (Custom RPC Title)

### ISSUE THREAD

**Issue by LeviSnoot** [Radiicall/jellyfin-rpc#16]
EDIT: Instead of making a whole new issue, I'm editing this post for clarity.

Would be great if the RPC state was "Watching" instead of "Playing".

OLD:

~~Is your feature request related to a problem? Please describe.~~
~~My instance title is customized but I don't want people outside my server members to know what it is.~~

~~Describe the solution you'd like~~
~~Adding a variable for the RPC title in `main.json`, which, when left blank defaults to the current behaviour, but when populated overrides the title for the RPC with the populated value.~~

~~Additional context~~
~~RPC Title = "Playing [RPC Title]"~~
~~Also would be good to change the RPC state from "Playing" to "Watching" since that's what you're doing ^^~~

**Comment by Radiicall** [comment]
The RPC title is not something I set to jellyfin, its what the app is called, if you go to the discord developer portal and make a new app with a different name and then use that appid then it will be called whatever you call your new app.

Also I have looked into changing it to "Watching" before but from what i can tell its not easy to do, I can look into it again but most likely its not happening.

**Comment by LeviSnoot** [comment]
That makes sense, I had a previous app that I used and it's called the same thing as my Jellyfin instance. Thanks for letting me know!

As for the latter part, I'm completely in the dark on Rust, but it looks to me like if you make use of Serenity in your script it does support `ActivityType`. I couldn't find anything like that in the docs for "discord_rich_presence" which I think is the library this project uses. You've probably already looked into all this but if not, it might help.

https://docs.rs/serenity/latest/serenity/model/gateway/enum.ActivityType.html

**Comment by Radiicall** [comment]
Serenity is a bot framework, I have used it before for bots but using it in this is not possible.
To get the watching status as a normal user you need oAuth2, I have thought about implementing it before but it requires a lot of work to make it happen.

**Comment by Radiicall** [comment]
There is no good way to do this without setting up some sort of oauth2, sadly i wont be doing it.
