### ISSUE TITLE
Default config file name is inconsistent and undocumented

### ISSUE THREAD

**Issue by 220111** [Radiicall/jellyfin-rpc#162]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

I was attempting to get this running today but I struggled to find where the default location for the config file should be. I looked at where it was pulling the default config from and even the function comment was inconsistent with the file name.

The comment mentions config.json (lines 184-184) but main.json is actually loaded (lines 194 & 198).

https://github.com/Radiicall/jellyfin-rpc/blob/2393f16cf294253721dd9b9c9d6682c87ce5b5ac/jellyfin-rpc-cli/src/config.rs#L178-L200

The error output for not having a default config and not specifying a config file is the following.

> 2024-10-23 17:53:32 INFO  [jellyfin_rpc] Initializing Jellyfin-RPC
thread 'main' panicked at C:\Users\tronl\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jellyfin-rpc-cli-1.3.0\src/main.rs:75:10:
config not found: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Describe the solution you'd like

1.  The function comment should be consistent with the functionality
2.  The wiki should mention the default config location
3.  A more detailed error code should be provided 

### Additional context

I am happy to submit these changes if someone can confirm that main.json is the intended filename.

**Comment by Radiicall** [comment]
Huh thats weird, the default filename has always been `main.json` (well apart from when it used a .env file) so I must've not been thinking straight while writing that comment.

If you want to create a fix for these then go ahead
