### ISSUE TITLE
Ability to toggle media types

### ISSUE THREAD

**Issue by aqsd91** [Radiicall/jellyfin-rpc#17]
**Is your feature request related to a problem? Please describe.**
I would like for people to see only the music im playing.
**Describe the solution you'd like**
The ability to toggle on or off certain media types (or librairies but that would be a best case scenario)

**Comment by Radiicall** [comment]
I'll look into adding this feature

**Comment by Radiicall** [comment]
I've added the feature to toggle media types, from what i can tell there is no way to find out what library you're watching/listening from but you can check here and tell me if you find anything https://api.jellyfin.org/
