### ISSUE TITLE
Ability to configure what music tags to show

### ISSUE THREAD

**Issue by xhao016** [Radiicall/jellyfin-rpc#24]
**Is your feature request related to a problem? Please describe.**
Currently it only display title, artist, genre and duration.  

**Describe the solution you'd like**
Ability to display different music tags in the discord such as album and year,  maybe make it configurable in the main.json?

**Describe alternatives you've considered**

**Additional context**
Love this program, thank you for the hard work!!

**Comment by Radiicall** [comment]
https://github.com/Radiicall/jellyfin-rpc/releases/tag/0.12.0-dev here, i made some changes. I need feedback on it because its not perfect and looks bad, but it works for now.

**Comment by Radiicall** [comment]
Okay i have now made the feature work better, it will be released with version 0.12.0
