### ISSUE TITLE
[Feature Request] Add button to the jellyfin instance + rename "Jellyfin" to the instance name

### ISSUE THREAD

**Issue by nanometer5088** [Radiicall/jellyfin-rpc#27]
**Is your feature request related to a problem? Please describe.**
Currently, the software only shows the media being played, and it's status.

<br>

**Describe the solution you'd like**
A way to add buttons and renaming "Jellyfin"
<br>

I'd love a button that links to my instance, and a way to rename the "Jellyfin" name to my instance name.

I made a horrible picture to better ilustrate what I mean:

![pic](https://i.imgur.com/c7hChpm.png)

<br>

BTW love your work :heart:

**Comment by Radiicall** [comment]
So first of all to change the "Jellyfin" name, you need to make an app on discords developer page with the name you want and then replace the application ID in the config.
![image](https://github.com/Radiicall/jellyfin-rpc/assets/66682497/7c24eece-0f84-424a-bf7d-2e3786aa3966)

Second of all I'll look into making custom buttons a thing

**Comment by Radiicall** [comment]
Feature added in db8d8a308fc7f8bfcabeab3e68cab0ec0ccf02ef, it will be a part of the next release
