### ISSUE TITLE
Random Rich Presence Clear

### ISSUE THREAD

**Issue by Cyx-Development** [Radiicall/jellyfin-rpc#33]
Jellyfin-RPC randomly clears the Rich Presence while the movie is still running.

**Screenshots**
https://i.imgur.com/v2xRen4.png

**Information:**
 - OS: Windows 11 Enterprise x64
 - Jellyfin Server Version: 10.8.10 (Windows Server x64)
- Jellyfin-RPC Version: 0.13.2

**Comment by Radiicall** [comment]
Does it do the same if you try watching in a browser instead of the app?

**Comment by Cyx-Development** [comment]
> Does it do the same if you try watching in a browser instead of the app?

In Browser it seems to work

**Comment by Radiicall** [comment]
It's related to #6 then, i have no idea what causes it

**Comment by Radiicall** [comment]
Maybe try updating to the newest jellyfin-media-player and see if that helps if you aren't on the newest one already

**Comment by Radiicall** [comment]
I'm not at home and this isn't something I can easily test right now, I will try to get it fixed when I get home

**Comment by Radiicall** [comment]
I can't reproduce this behavior on linux or windows (in a VM)
