### ISSUE TITLE
Audiobook Presence

### ISSUE THREAD

**Issue by Radiicall** [Radiicall/jellyfin-rpc#35]
### Discussed in https://github.com/Radiicall/jellyfin-rpc/discussions/34

<div type='discussions-op-text'>

<sup>Originally posted by **0xGingi** July 13, 2023</sup>
Would it be possible to display the presence of audiobooks for libraries using the Books Library type?</div>

**Comment by Radiicall** [comment]
Thoughts @0xGingi?
![image](https://github.com/Radiicall/jellyfin-rpc/assets/66682497/b9603e01-ac40-4a5a-a96c-eb0fd7cbbb9e)

Let me know if its missing something, its currently displaying the name of the book, the writer and what genres

**Comment by 0xGingi** [comment]
Yeah, that looks pretty good, I'll compile the audiobook branch in a bit and try it out

**Comment by 0xGingi** [comment]
![image](https://github.com/Radiicall/jellyfin-rpc/assets/104647854/5861d46d-55b7-438c-b791-eca96e1c29bf)

It's working perfect, thanks for adding support for this!

**Comment by Radiicall** [comment]
I'll try to fix it up a bit before merging, i want it to say "Shirtaloon and Travis Deverell" instead of "Shirtaloon, Travis Deverell". Also i might add customization to this like i did for music presence, it seems to work about the same
