### ISSUE TITLE
SSL issue?

### ISSUE THREAD

**Issue by SirObby** [Radiicall/jellyfin-rpc#37]
**Describe the bug**
Errors when starting, doesn't connect to Discord basically.

**To Reproduce**
./jellyfin-rpc-x86_64-linux

**Expected behavior**
it runs?

**Screenshots**
LOG:
------------------------------------------------------------------
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8096), path: "/Sessions", query: Some("api_key=543b71cfe4db45058ffd6c810a0264b1"), fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772427, library: "SSL routines", function: "ssl3_get_record", reason: "wrong version number", file: "ssl/record/ssl3_record.c", line: 354 }]))) }, X509VerifyResult { code: 0, error: "ok" })) }

**Information:**
 - OS: [e.g. Gentoo Linux]
 - Jellyfin Server Version: [e.g.10.8.10]
- Jellyfin-RPC Version: [e.g. 0.13.2 attempt 2]

**Additional context**
I had some problems with OpenSSL on my system, that might be it.

**Comment by 0xGingi** [comment]
Either try using http on port 8096, or if you have a https configured/a self signed cert since you're using localhost , try using port 8920, which is the default https port on jellyfin.

**Comment by Radiicall** [comment]
Is this resolved?

**Comment by SirObby** [comment]
Sorry I got this email really late, I'm going to check on this tomorrow.

**Comment by SirObby** [comment]
:( I am an idiot yeah I didn't notice this was https://localhost than http://localhost.
