### ISSUE TITLE
Jellyfin-RPC crash when playing theme music

### ISSUE THREAD

**Issue by Palou-King** [Radiicall/jellyfin-rpc#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Jellyfin-rpc crash when theme music is playing in the background. Crash does not happen when Theme Music is disabled in the settings under Display. Dont Crash with Theme Videos.

### Terminal output

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### Jellyfin-RPC version

0.14.0

### What OS are you using?

Windows 11

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
Fixed in #44, will be a part of the 0.14.1 update
