### ISSUE TITLE
Program (.exe binary) not launching

### ISSUE THREAD

**Issue by elendil7** [Radiicall/jellyfin-rpc#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Tried launching jellyfin-rpc.exe, and it launched a blank CMD window which automatically closes a few milliseconds later. No logs or errors printed.

### Terminal output

No output - cmd window closes right after opening launching it.

### Jellyfin-RPC version

0.14.1

### What OS are you using?

Windows 10 Pro

### What version is the Jellyfin server on?

10.8.9

**Comment by Radiicall** [comment]
Try opening a powershell or cmd window in the same directory then do `./jellyfin-rpc.exe`

**Comment by elendil7** [comment]
### Getting this via powershell:
```bash
←[1;31mConfig can't be loaded: Io("Unable to open file: The system cannot find the file specified. (os error 2)").
Config file should be located at:←[0m C:\Users\<USERNAME>\AppData\Roaming\jellyfin-rpc\main.json
```

### Getting this via CMD:
```bash
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by elendil7** [comment]
Fixed. Works after adding `C:\Users\<username>\AppData\Roaming\jellyfin-rpc\main.json` file and filling it in with configuration options.
