### ISSUE TITLE
Make a proper tutorial to understand how to install it

### ISSUE THREAD

**Issue by Gauvino** [Radiicall/jellyfin-rpc#46]
**Is your feature request related to a problem? Please describe.**
For a beginner like me, I can't understand on how to install the client, the doc is incomprehensible.
Could you be please making a good tutorial like a video or just a doc with everything describe in it?

**Comment by Sayykii** [comment]
Hello fellow github user,  I think the doc is very much comprehensible, it explains every step in great detail. Which part is confusing you exactly?

**Comment by Uruknara** [comment]
How to install jellyfin-rpc simply

**Comment by Caassiiee** [comment]
it's incredibly easy but ill make a video tutorial later O.o

**Comment by 0xGingi** [comment]
I've made a quick install video guide

https://www.youtube.com/watch?v=erYuN_Sz1UQ
