### ISSUE TITLE
Crash when playing music (linux)

### ISSUE THREAD

**Issue by YazZHh** [Radiicall/jellyfin-rpc#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Loading music within jellyfin crashes jellyfin-rpc on linux. Works as expected for videos.

### Terminal output

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/services/jellyfin.rs:267:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Jellyfin-RPC version

0.14.1

### What OS are you using?

Linux Mint 21.2 Cinnamon

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
what sort of music? Like what's the library type set to?

**Comment by YazZHh** [comment]
I've set the library type to Music, see the image :
![IMG_20230810_233340](https://github.com/Radiicall/jellyfin-rpc/assets/88186277/a2f37b03-857c-417b-b637-52b971747a13)
(Oh and yeah "Musique" is the french for music)

**Comment by YazZHh** [comment]
1.14.0 crashes with exactly the same error in 0.14.1.

**Comment by Radiicall** [comment]
A fix will be included in 0.14.2
