### ISSUE TITLE
Intermittent disconnecting from Discord RPC causes jellyfin-rpc to seemingly flicker

### ISSUE THREAD

**Issue by StayBlue** [Radiicall/jellyfin-rpc#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

I'm not sure what conditions cause this bug to occur, but the Jellyfin rich presence comes and goes from my profile, almost as if it's flickering.

Sometimes, it stops working entirely until I restart my PC.

### Terminal output
```
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
アンダーヒロイン
By ツユ - J-Pop
```

### Jellyfin-RPC version

0.14.1

### What OS are you using?

Windows 11 22H2

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
If this is related to #6 and #33 then its a network issue and i have no idea what causes it or how to fix it, check your firewall rules and do [this](https://github.com/Radiicall/jellyfin-rpc/issues/6#issuecomment-1445352936) to confirm that its the same issue

**Comment by Radiicall** [comment]
Is this resolved?

**Comment by StayBlue** [comment]
It hasn't been resolved, as it still happens. I just haven't gotten the time to review the issues and do what you told me to do.

**Comment by StayBlue** [comment]
Not sure what has happened since I have opened this issue, but the issue hasn't popped up again for a while, so I'm closing this issue for now until I can reproduce it again.
