### ISSUE TITLE
Cover art without port forwarding

### ISSUE THREAD

**Issue by Pickymarker** [Radiicall/jellyfin-rpc#5]
how do i get cover art to show up on jellyfin-rpc without needing to port forward using only one pc that has server and rpc on same pc

**Comment by Radiicall** [comment]
Hey, sadly for right now this can't be done, I might try to implement a way to do it in the future.

Discord needs a URL for images and if the server isn't port forwarded then discord can't display it.

**Comment by Pickymarker** [comment]
then how do i port forwarding it using nginx or play.it so something similar and not have to use router port forwarding

**Comment by Radiicall** [comment]
I'm going to check if I can implement the IMDb api later today for images.

**Comment by Pickymarker** [comment]
okay

**Comment by Radiicall** [comment]
> I'm going to check if I can implement the IMDb api later today for images.

The IMDb API can't be used for this... I'm keeping this issue open for now as this is something I want to solve in the future.

**Comment by Pickymarker** [comment]
then is there a way to port forward without using router port forwarding like nginx or playit.gg or something similar

**Comment by Radiicall** [comment]
> Back in the day, I used to run [phin05/discord-rich-presence-plex](https://github.com/phin05/discord-rich-presence-plex) and they got around the issue by having you provide an imgur application ID, essentially an api key in the .env. I'm not sure how applicable this would be to in the case of your project, but I thought I'd mention it. 

I was trying to do this but the only imgur api crate is linux only from what i could tell

**Comment by Radiicall** [comment]
This will be implemented through imgur in the next update
