### ISSUE TITLE
Link AUR packages in README

### ISSUE THREAD

**Issue by Maxr1998** [Radiicall/jellyfin-rpc#50]
I just submitted a PKGBUILD for your package to the AUR so that users on Arch Linux can easily install it on their system: https://aur.archlinux.org/packages/jellyfin-rpc

Coincidentally, another user submitted the git distribution (which always builds the latest master) just a few hours earlier, which you can find here: https://aur.archlinux.org/packages/jellyfin-rpc-git.

Both of these packages can be linked so that users could choose between stable releases and the latest and greatest (and perhaps less stable).
Thanks!

**Comment by Radiicall** [comment]
I'll be linking the aur packages in the readme soon, i just want to look over them first

**Comment by Maxr1998** [comment]
Sure, and thanks! I tried to follow the packaging guidelines for rust as closely as I could, but lmk if you have any suggestions. By the way, would it make sense to commit the Cargo.lock to the repo so that the dependencies are deterministic?

**Comment by Radiicall** [comment]
I can remove the Cargo.lock from the gitignore file and upload mine to the repo

**Comment by Maxr1998** [comment]
Yes, sounds good.

**Comment by 0xGingi** [comment]
Added https://aur.archlinux.org/packages/jellyfin-rpc-bin and modified both -git and -bin to match your install locations, conflicts...etc

**Comment by Radiicall** [comment]
I updated the README but im not sure how i should format this, if you two have any ideas then that would be great because its kinda messy right now

**Comment by Radiicall** [comment]
I've figured out a solution but its gonna take me a while to set up, ill be trying to make a wiki page for this project instead of only having a readme

**Comment by Maxr1998** [comment]
> Added https://aur.archlinux.org/packages/jellyfin-rpc-bin and modified both -git and -bin to match your install locations, conflicts...etc

Awesome, thank you! Note that you don't have to list all variants in the conflicts, just the main package without any suffix is enough. Also, the provides should be the package without the suffix as well.

And lastly, you might want to reuse the service file from this repo and patch it with sed in prepare like I do, then you don't need to maintain a separate copy for it.

**Comment by Radiicall** [comment]
I just pushed the Cargo.lock file, i completely forgot about it until now!

**Comment by Maxr1998** [comment]
Awesome! Once there is a new release, I should then be able to add the `--locked` switch to [the fetch step](https://wiki.archlinux.org/title/Rust_package_guidelines#Prepare).

**Comment by 0xGingi** [comment]
Trying to build with --locked in fetch, but getting error "Cargo.lock needs to be updated but --locked was passed to prevent this"

**Comment by Radiicall** [comment]
Yeah i need to update it, i can do it right now
