### ISSUE TITLE
Images only sometimes work

### ISSUE THREAD

**Issue by amarevite** [Radiicall/jellyfin-rpc#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

I have my Jellyfin server behind Caddy + my own domain. For some albums (and the couple videos I've checked so far), images display totally fine. Often (usually?) though, the images won't display at all.

### Jellyfin-RPC version

0.14.2

### What OS are you using?

Windows 10 Pro

### What version is the Jellyfin server on?

10.8.10

### Anything else?

Here are two different songs on two different albums:

![image](https://github.com/Radiicall/jellyfin-rpc/assets/35640607/7266d685-ae24-4c2c-a10a-7eaaa530e429)
![image](https://github.com/Radiicall/jellyfin-rpc/assets/35640607/61001bdb-3bd4-4f03-bea9-262babda9f90)

I have `enable_images` set to `true` and `imgur_images` set to `false`. Jellyfin-RPC's config connects to my domain rather than over LAN (`https://` included). Restarting Jellyfin-RPC does not resolve the issue. In case it's relevant, I use Armcord (which integrates arRPC for rpc support). This has been a problem since at least 1.14.1 (when I started using Jellyfin-RPC). I haven't found anything that might indicate what's causing the problem.

**Comment by Radiicall** [comment]
Can you check if the images work when using imgur, im not sure if this is related to jellyfin-rpc at all because i personally dont use the imgur feature either and i dont have this problem

**Comment by amarevite** [comment]
From what I can tell, that didn't fix the issue. I'm not sure if I set up imgur properly but I'm not seeing any errors after closing jrpc, updating my config, then launching it again. `imgur_images` is set to `true` and I've filled out the `imgur` `client_id` value.

**Comment by Radiicall** [comment]
Im guessing jellyfin-rpc is having trouble reading the image files or maybe discord is having trouble reading them, if you open up your config directory there should be a file called `urls.json` in there, can you provide the contents of the file?

**Comment by Radiicall** [comment]
It just contains the id of the content and then what URL it got uploaded to on imgur, its to not upload duplicates and upset the people over at imgur

**Comment by amarevite** [comment]
Okay I accidentally restarted armcord while doing something else and now everything is working, so this might be an issue on armcord/arrpc's end rather than on jellyfin-rpc's end. The `urls.json` file was filled with info so imgur uploading was working, and I just reverted my config and things are still working. So I think this is more likely to be a problem with armcord and/or arrpc than with jellyfin-rpc. Sorry for the trouble!

**Comment by Radiicall** [comment]
Check if your friends can still see the images even if you can't do it. I'll close the issue for now, reopen this or make a new issue if it turns out its actually related
