### ISSUE TITLE
Windows defender

### ISSUE THREAD

**Issue by powerdoll** [Radiicall/jellyfin-rpc#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Whenever i install it the window defender blocks/deletes the file, i made an exception but idk whats the real issue about it

### Jellyfin-RPC version

0.14.0

### What OS are you using?

W11

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
I see you wrote you're using 0.14.0, does the same happen on the newest version 0.14.2?

**Comment by Caassiiee** [comment]
its actually 0.14.2 i forgot to change that by default is on 0.14.0, anyway, yeah in 0.14.2 that is what happens, and the auto run at startup on windows doesn't work for some reason, i reinstalled and still the same, i have to manually run it and keep the terminal open

**Comment by Radiicall** [comment]
What did defender say it detected? It might have something to do with rustls

**Comment by Caassiiee** [comment]
> What did defender say it detected? It might have something to do with rustls

< Bearfoos.B!ml > so a false positive, but even with the exception it keeps deleting the jellyfin-rpc.exe

**Comment by 0xGingi** [comment]
It's helpful, that anytime you encounter a false positive to submit the exe to https://www.microsoft.com/en-us/wdsi/filesubmission and report it as a false positive

![image](https://github.com/Radiicall/jellyfin-rpc/assets/104647854/c6fe140b-4032-40a8-98f5-49396d182614)

**Comment by 0xGingi** [comment]
Update: They removed the detection

![image](https://github.com/Radiicall/jellyfin-rpc/assets/104647854/56343f13-5c9b-464f-850d-9c79a18d0073)

**Comment by Radiicall** [comment]
oh great! Thanks @0xGingi

**Comment by Radiicall** [comment]
> > What did defender say it detected? It might have something to do with rustls
> 
> < Bearfoos.B!ml > so a false positive, but even with the exception it keeps deleting the jellyfin-rpc.exe

If it still gets detected after updating your malware definitions then you should probably check that you dont have *actual* malware somewhere on your computer

**Comment by Caassiiee** [comment]
> 
well it doesnt get deleted anymore but i cant make it auto-run at start up again, i changed even the api key from jellyfin and still doesnt work reinstalling it :C

**Comment by Radiicall** [comment]
> > 
> 
> well it doesnt get deleted anymore but i cant make it auto-run at start up again, i changed even the api key from jellyfin and still doesnt work reinstalling it :C

Press win+r, write `services.msc` and press enter, look for jellyfin-rpc in the list and check if its set to "Automatic"

**Comment by Caassiiee** [comment]
it is, but whenever i run it it stops automatically, i deleted all the files from, ill try tomorrow deleting the service and start over

**Comment by Radiicall** [comment]
> it is, but whenever i run it it stops automatically, i deleted all the files from appdata too but it doesnt seem to work properly, ill try tomorrow deleting the service and start over

Did this get resolved?

**Comment by powerdoll** [comment]
yeah, actually i had to delete it in regedit then the appdata folder, restarted, installed again, working fine

**Comment by powerdoll** [comment]
nvm, it crashes for some reason

**Comment by 0xGingi** [comment]
Could you check Windows Event Log and in the Applications section see if there's any log for the jellyfin-rpc service
