### ISSUE TITLE
Panic when no imgur image found

### ISSUE THREAD

**Issue by 0xGingi** [Radiicall/jellyfin-rpc#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

When no imgur image is found, jellyfin-rpc panics rather than showing no image

### Terminal output

thread 'main' panicked at 'imgur returned no image url!', src/services/imgur.rs:118:14

### Jellyfin-RPC version

0.14.3

### What OS are you using?

Arch

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
It panicked because it tried uploading the file but imgur didnt return a URL in the response, might have to handle this in a better way...
