### ISSUE TITLE
128 character length limit

### ISSUE THREAD

**Issue by nyouness** [Radiicall/jellyfin-rpc#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

![Screenshot 2023-08-26 001906](https://github.com/Radiicall/jellyfin-rpc/assets/117232906/9b8d6349-c826-4481-94f6-8cc44012739a)
![Screenshot 2023-08-26 001921](https://github.com/Radiicall/jellyfin-rpc/assets/117232906/4fa8eaa0-b0e9-4ddf-a8b3-579b0b4e3f63)
![Screenshot 2023-08-26 001956](https://github.com/Radiicall/jellyfin-rpc/assets/117232906/30c5b360-5dd5-4e7f-82ad-1cc10a15d05e)
![Screenshot 2023-08-26 002008](https://github.com/Radiicall/jellyfin-rpc/assets/117232906/feaa9b6a-f290-496d-ac7e-e6b27e6b6e41)
![Screenshot 2023-08-26 002023](https://github.com/Radiicall/jellyfin-rpc/assets/117232906/53d3b1f1-619b-485e-9248-9e6c23337a2b)

The other album shows fine and the other not.

### Jellyfin-RPC version

0.14.4

### What OS are you using?

windows

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
I think it might be related to the length of the message, i might have to slice it at a certain point

**Comment by nyouness** [comment]
yeah i think because of long title of album , i will update title of the album and see and. Thank you for making this project and replaying.

**Comment by Radiicall** [comment]
I'll check it too when i have time, if that is the case then it'll be fixed in 0.14.5 or 0.15.0

**Comment by nyouness** [comment]
yes please fix it and ty again for replaying!

**Comment by Radiicall** [comment]
[jellyfin-rpc.zip](https://github.com/Radiicall/jellyfin-rpc/files/12445469/jellyfin-rpc.zip) here's an exe for you to test with

**Comment by nyouness** [comment]
![Screenshot 2023-08-26 154023](https://github.com/Radiicall/jellyfin-rpc/assets/117232906/2e900b63-0612-45d9-bee8-b92490852bf8)

thanks a loot its working!
