### ISSUE TITLE
Doesnt work or crashes

### ISSUE THREAD

**Issue by powerdoll** [Radiicall/jellyfin-rpc#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

i turn on my pc, it works for a few mins or songs thenit crashes and it just doesnt want to work again even if i finish the process or restart jellyfin and discord too
![image](https://github.com/Radiicall/jellyfin-rpc/assets/105698999/b91c99b5-2833-4773-b561-98fe1bdeca07)

### Terminal output

![image](https://github.com/Radiicall/jellyfin-rpc/assets/105698999/cd64459c-fbf6-4a98-bc29-17322258cadf)

### Jellyfin-RPC version

0.14.4

### What OS are you using?

Windows 11

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
"Trying to connect" means its trying to connect to discord, you have rich presence enabled in settings on the client right?

**Comment by powerdoll** [comment]
yes i do and i know.

sometimes its just stuck in attempting to connect to socket something like that

it crashes while playing, it cleans the status itslef, then next song plays, it shows up, then next one plays and then it crashes

**Comment by Radiicall** [comment]
> Perhaps it has to do with the particular song that plays when it crashes?

It could be related to #61, if the program tries to connect to discord too many times too fast it uses a while to connect again. Like if you start and stop the program more than 4 times it takes a while to connect because discord is rate limiting or something

**Comment by Radiicall** [comment]
Please update to [0.14.7](https://github.com/Radiicall/jellyfin-rpc/releases/tag/0.14.7)

**Comment by Radiicall** [comment]
Closing issue because of no more replies, if you're still having this problem then please reopen this or open a new issue
