### ISSUE TITLE
RPC keeps resetting

### ISSUE THREAD

**Issue by Valoriks** [Radiicall/jellyfin-rpc#6]
**Describe the bug**
As shown in the included video, it connects to the API but when I start playing media it shows in the RPC output and clears itself after couple of seconds. It then cycles between playing media and clearing the output. It's also visible on Discord, where it shows what I'm playing and suddenly disappears. 

**Screenshots**
https://user-images.githubusercontent.com/97224849/221376752-86e81d59-c1d8-4f71-96de-35f75f5aeb6d.mp4

**Information:**
 - Server OS: Raspberry Pi OS
 - OS: Arch Linux
 - Jellyfin Server Version: 10.8.8
- Jellyfin-RPC Version: 0.7.0
- Jellyfin client: Jellyfin Media Player 1.8.1

**Additional context**
Jellyfin-rpc config file without the API key:
[jellyfin-rpc.env.txt](https://github.com/Radiicall/jellyfin-rpc/files/10832188/jellyfin-rpc.env.txt)

**Comment by Radiicall** [comment]
Can you test with <a href="https://github.com/Radiicall/jellyfin-rpc/files/10832237/jellyfin-rpc.zip">this binary</a>, I increased the sleep duration from 750ms to 2s. The RPi might not like how often its checking what's playing.

Also what Pi model are you using?

**Comment by Valoriks** [comment]
The issue still remains with this new binary. I host my Jellyfin sever on Raspberry Pi 4B with 4 GB RAM.

**Comment by haileyhapi** [comment]
I tried and I could not recreate this issue on my end.

I'm using the exe binary.

**Comment by Radiicall** [comment]
> The issue still remains with this new binary. I host my Jellyfin server on Raspberry Pi 4B with 4 GB RAM.

if you check `<jellyfinurl>/Sessions?api_key=<api_key>` while playing a video, then go into `0>NowPlayingItem` and then try to reload a few times. Does it disappear?

**Comment by Valoriks** [comment]
It does... So it seems to be something with the API.

https://user-images.githubusercontent.com/97224849/221414428-7406f825-d937-4336-ab38-75349e1f6fc9.mp4

**Comment by Radiicall** [comment]
hmm that's odd... Are you using a third party client or is it the official one for jellyfin?

**Comment by Valoriks** [comment]
It should be the official one from AUR
https://aur.archlinux.org/packages/jellyfin-media-player

**Comment by Radiicall** [comment]
Does the same thing happen if you try playing from a browser? I use the official one from flathub currently

**Comment by Valoriks** [comment]
I tried it right now in Firefox. It's no problem there. If you have no issues with Jellyfin Media Player from Flathub, I'll try that

**Comment by Radiicall** [comment]
Okay, report back if it works or not!

**Comment by Valoriks** [comment]
Seems to be working with Jellyfin Media Player from Flathub

**Comment by Valoriks** [comment]
I forgot to add that both binaries (from Release page) and the edited one work fine, so there's no need to update.
