### ISSUE TITLE
[Suggestion] Change the default Playing Jellyfin to Listening to/Watching Jellyfin

### ISSUE THREAD

**Issue by Zyztem** [Radiicall/jellyfin-rpc#60]
**Is your feature request related to a problem? Please describe.**
Not a problem, more of a suggestion and enhancement.
**Describe the solution you'd like**
For the default presence to be changed from Playing to Watching when watching something on jellyfin and Listening to when listening to something on jellyfin.

**Describe alternatives you've considered**
I haven't thought of any other solutions.

**Additional context**
![image](https://github.com/Radiicall/jellyfin-rpc/assets/66957203/f3f54f9e-7d0f-46ac-863d-8c43dd447482)

**Comment by Radiicall** [comment]
this cant be done with normal rich presence, it requires using oauth2 and you need permission from discord themselves to implement this feature, that means i would need to obfuscate code to include a key for this to work.. It would be a mess. https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes look at activities.write
