### ISSUE TITLE
Long album title with CJK characters crashes program

### ISSUE THREAD

**Issue by SightSpirit** [Radiicall/jellyfin-rpc#61]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What went wrong?

When playing a song with a long, bilingual album title with a CJK character at the new cutoff, the jellyfin-rpc process shuts down. I have tried running the executable directly from the desktop and from the command line and gotten the same result.

### Terminal output

```
thread 'main' panicked at 'byte index 128 is not a char boundary; it is inside 'ス' (bytes 126..129) of `By Nintendo - The Legend of Zelda: Twilight Princess HD Original Soundtrack (ゼルダの伝説 トワイライトプリンセス HD オリジナルサウンド
トラック) - 2016`', src\services\jellyfin.rs:130:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Jellyfin-RPC version

0.14.5

### What OS are you using?

Windows 11 (22H2)

### What version is the Jellyfin server on?

10.8.10

**Comment by Radiicall** [comment]
Yeah i did not think about this, need to figure out how i'll handle that
