### ISSUE TITLE
Windows Defender (and Google Chrome) falsely detect the program as malware.

### ISSUE THREAD

**Issue by SomeCuteDoragons** [Radiicall/jellyfin-rpc#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Windows Defender falsely detects the program as malware containing "Trojan:Win32/Bearfoos.A!ml" and gets rid of the file. Google Chrome also sees the program as something suspicious but after scanning it, it sees no problem and allows it to be saved. 

### Jellyfin-RPC version

0.14.6

### What OS are you using?

Windows 11 Pro (Canary Insider Preview)

### What version is the Jellyfin server on?

10.8.10

### Anything else?

![image](https://github.com/Radiicall/jellyfin-rpc/assets/47637144/b3631ec0-8713-4ffd-b94b-c559dc040d6f)
![image](https://github.com/Radiicall/jellyfin-rpc/assets/47637144/b57fca3a-da30-4ff1-b1b9-2f40df9a4d6a)
![image](https://github.com/Radiicall/jellyfin-rpc/assets/47637144/a2ce16a4-7c74-4347-bd24-516c0be1bf4f)

**Comment by Radiicall** [comment]
Reported it to microsoft
![image](https://github.com/Radiicall/jellyfin-rpc/assets/66682497/39d29191-254e-4498-a78a-a95283970884)

**Comment by Radiicall** [comment]
![image](https://github.com/Radiicall/jellyfin-rpc/assets/66682497/d8da9bcc-bbd2-4fb2-9297-17a593e02252)
