### ISSUE TITLE
Keeps disconnecting from from Discord and struggling/not reconnecting

### ISSUE THREAD

**Issue by againstpetra** [Radiicall/jellyfin-rpc#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

I'm using jellyfin-rpc via a launchctl service. It starts up and works well for a maybe 30 seconds, and then just randomly disconnects. It struggles with reconnecting, often it just doesn't for a long time.

### Terminal output

stdout:

```

Notice Me
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Gone Girl
By SZA
Attempt 1: Trying to reconnect
```

stderr (this may just be from when I relaunch Discord):

```
Failed to reconnect, retrying soon
Failed to reconnect, retrying soon
Failed to reconnect, retrying soon
```

### Jellyfin-RPC version

0.14.5

### What OS are you using?

macOS

### What version is the Jellyfin server on?

10.8.10

### Anything else?

Restarting jellyfin-rpc, I don't see it connect back to Discord immediately. If I restart Discord though, jellyfin-rpc connects again fine and works for a little bit.

**Comment by Radiicall** [comment]
Please update to [0.14.7](https://github.com/Radiicall/jellyfin-rpc/releases/tag/0.14.7)

**Comment by againstpetra** [comment]
I'm still not seeing anything interesting in stdout or srderr. stdout:

```
~ ❮ tail -f /tmp/jellyfinrpc.local.stdout.txt
Pay No Mind
By Beach House
//////////////////////////////////////////////////////////////////
                          Jellyfin-RPC
------------------------------------------------------------------
Attempt 1: Trying to connect
Connected to Discord Rich Presence Socket
------------------------------------------------------------------
Dark Spring
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Dark Spring
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Dark Spring
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Dark Spring
By Beach House
------------------------------------------------------------------
Cleared Rich Presence
------------------------------------------------------------------
Pay No Mind
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Pay No Mind
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Pay No Mind
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Pay No Mind
By Beach House
Attempt 1: Trying to reconnect
Reconnected to Discord Rich Presence Socket
------------------------------------------------------------------

Pay No Mind
By Beach House
```

stderr is empty of new lines (just `Failed to reconnect, retrying soon` a few times)

**Comment by Radiicall** [comment]
[Binaries.zip](https://github.com/Radiicall/jellyfin-rpc/files/12566939/Binaries.zip) these binaries are based on c008fd3e476d01107de219ae173c95f3e2c1e12d try checking if this prints a useful error

**Comment by againstpetra** [comment]
okay, this gave some interesting logs in stderr:

```
Failed to set activity
Error: Broken pipe (os error 32)
Failed to set activity
Error: Broken pipe (os error 32)
Failed to set activity
Error: Broken pipe (os error 32)
```

**Comment by Radiicall** [comment]
> okay, this gave some interesting logs in stderr:
> 
> 
> 
> ```
> 
> Failed to set activity
> 
> Error: Broken pipe (os error 32)
> 
> Failed to set activity
> 
> Error: Broken pipe (os error 32)
> 
> Failed to set activity
> 
> Error: Broken pipe (os error 32)
> 
> ```

Have you checked your RAM usage? macOS is very good at suspending applications and that _could_ lead to broken pipe…

**Comment by againstpetra** [comment]
memory is showing ~9gb used out of 16, so it does have free memory. I guess it could be Discord getting suspended, though it happens both on battery power and when the laptop is plugged in iirc.

as I write this, I only have my terminal, browser, and discord open, so it isn't under high load or anything.

I guess it could still be macOS doing something to Discord. do you know some way to make Discord exempt from that, to test if that fixes the issue? alternatively, is there anything in the code that could be done to workaround macOS suspending Discord?

**Comment by Radiicall** [comment]
> memory is showing ~9gb used out of 16, so it does have free memory. I guess it could be Discord getting suspended, though it happens both on battery power and when the laptop is plugged in iirc.
> 
> 
> 
> as I write this, I only have my terminal, browser, and discord open, so it isn't under high load or anything.
> 
> 
> 
> I guess it could still be macOS doing something to Discord. do you know some way to make Discord exempt from that, to test if that fixes the issue? alternatively, is there anything in the code that could be done to workaround macOS suspending Discord?
> 
> 
> 
> I'm trying it out now, and I am seeing the error message pop up as soon as I switch from Discord to my browser. so it could well be macOS messing with discord...

Do you have low power mode enabled?

**Comment by againstpetra** [comment]
no, and it still happens when the laptop's power adapter is plugged in

**Comment by Radiicall** [comment]
> no, and it still happens when the laptop's power adapter is plugged in
> 
> 
> 
> it even happens when I'm tabbed in on Discord and have it focussed, but stop actively using the laptop for a few seconds. even if macOS is this aggressive, do other programs have similar issues? like spotify etc...

What version of macOS are you on?
This behavior doesnt sound right, I've never noticed macOS being that aggressive.

Spotify uses oauth2 for discord status so it doesnt need discord on the client that's playing the song.

**Comment by againstpetra** [comment]
13.5.2.

would you accept a PR that implements oauth2?

**Comment by Radiicall** [comment]
> 13.5.2.
> 
> 
> 
> would you accept a PR that implements oauth2?

You need explicit permission from discord to get access to setting status through oauth2, and if i did get that permission then i would have to start obfuscating code

**Comment by againstpetra** [comment]
> i would have to start obfuscating code

oh, how come? to hide an API key or something?

**Comment by Radiicall** [comment]
> > i would have to start obfuscating code
> 
> oh, how come? to hide an API key or something?

hiding secrets needed for oauth2, yes.

**Comment by againstpetra** [comment]
can users put in their own token that they obtain from the discord developer portal?

**Comment by Radiicall** [comment]
> can users put in their own token that they obtain from the discord developer portal?

I do want the feature but as long as discord requires you to have explicit permission from them for it, I dont want to implement it, It's a lot of trouble for something only some people will be able to use.

**Comment by againstpetra** [comment]
hm, I'm interested about this process of requesting discord's permission, could you link to something about it? I can't find information about the process

**Comment by Radiicall** [comment]
https://discord.com/developers/docs/topics/oauth2
<img width="960" alt="image" src="https://github.com/Radiicall/jellyfin-rpc/assets/66682497/88c1e463-41d9-40ff-82de-72af11bb1a0b">

**Comment by Radiicall** [comment]
> do you know how other modules, e.g. [this](https://discordjs.guide/popular-topics/faq.html#how-do-i-set-my-status-to-watching-listening-to-competing-in), are doing it then? their code is open
> 
> 
> 
> I noticed this (emphasis mine):
> 
> 
> 
> > Requesting them from a user without approval from Discord **may** cause errors or undocumented behavior in the OAuth2 flow.
> 
> 
> 
> I'm getting the feeling that the warning about needing their approval isn't necessarily the case, like a lot of things with discord bots / their APIs

I have personally tested this and you **do** need approval, bots are bots not users so that discord.js thing has nothing to do with this. This isnt constructive anymore, I've told you its not happening for now

**Comment by Radiicall** [comment]
Sorry for not entertaining the idea, ive looked into it before as i said… #16 and #60. 
I tested this a little while back and you can't grant the activities.write scope properly, it has some error like permission denied or invalid scope or something.

It's not doable without testing and I can't test it without access to the feature, I wish this was something I could easily implement (because it has extra features) but it isnt.
And with the low amount of people that will have access to it anyways its not worth it to try to get it implemented…

**Comment by Radiicall** [comment]
Please rerun the installer, i noticed a mistake that might've caused issues

**Comment by Radiicall** [comment]
> Please redownload and run the installer, i noticed a mistake that caused issues on macOS

Hey, im pretty sure this is solved if you try this

**Comment by againstpetra** [comment]
nope, not solved

**Comment by Radiicall** [comment]
> nope, not solved

you did redownload the installer file right?

**Comment by againstpetra** [comment]
I never used the installer. I download the binary manually.

**Comment by Radiicall** [comment]
Have you tried any previous versions and checked if the same issue happens? like 0.13 or lower. Also can you send me your config file without imgur client id, jellyfin url or jellyfin api key? I want to see what config options you're using
