### ISSUE TITLE
RPC not connecting to jellyfin website

### ISSUE THREAD

**Issue by Alecsis** [Radiicall/jellyfin-rpc#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

I am using local DNS for Jellyfin and I can visit the site in the browser but with RPC it doesn't work 

### Terminal output

thread 'main' panicked at 'Can't unwrap URL, check if JELLYFIN_URL is correct. Current URL: https://jellyfin.refly.duckdns.org/', src\services\jellyfin.rs:90:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Jellyfin-RPC version

0.14.6

### What OS are you using?

Windows 11 Education

### What version is the Jellyfin server on?

10.8.10

### Anything else?

![image](https://github.com/Radiicall/jellyfin-rpc/assets/114525637/b1892e88-e9d5-40bb-95f8-a8815949d6ef)

![image](https://github.com/Radiicall/jellyfin-rpc/assets/114525637/1b614dad-6084-472c-9bf0-900a0b6395d2)

**Comment by 0xGingi** [comment]
i notice you're using /false for jellyfin, try making the url https://jellyfin.refly.duckdns.org/false/

**Comment by Alecsis** [comment]
woww tysm it turns out that the base URL had been set to "/false" and I didn't realise that but thanks! works good now!
