### ISSUE TITLE
Time remaining should not show when media is paused

### ISSUE THREAD

**Issue by tilda** [Radiicall/jellyfin-rpc#7]
**Is your feature request related to a problem? Please describe.**
Basically I think it looks weird when the "xx:xx left" keeps resetting every time the presence is set (every couple of seconds).

**Describe the solution you'd like**
In its place, a small icon for it would be nice. Could also have "Paused" but I don't think Discord gives room for that.

**Describe alternatives you've considered**
Dealing with it (but I don't want to)

**Additional context**
Another thing on the topic of timestamps since I don't feel like making another issue: how about setting start time as well? [discord_rich_presence has a function for it](https://docs.rs/discord-rich-presence/latest/discord_rich_presence/activity/struct.Timestamps.html#method.start) that can be combined with the `end` you already use - and you can likely gather start times from Jellyfin's `ActivityLog` API.

**Comment by Radiicall** [comment]
Hi, I'm pretty sure start time can't be used while end time is in use.

Having an icon for when its paused would probably be better yes, I might look into it tomorrow or on Monday

**Comment by tilda** [comment]
[The example payload used in Discord's documentation](https://discord.com/developers/docs/topics/rpc#setactivity-example-set-activity-payload) doesn't say anything about that - it might be worth a try tbh.

**Comment by Radiicall** [comment]
What would be the benefit of having both start time and end time though? I think personally keeping just the end time might be better, cluttering the presence too much doesnt look good. I might look into adding a toggle but we'll see.

**Comment by tilda** [comment]
I guess it does come down to personal preference - iirc it gives a progress bar similar to what you would see on Spotify's presence and I like that better than a "xx:xx left"

**Comment by Radiicall** [comment]
I dont think the Spotify presence adheres to the same rules as normal presence, it's _too_ perfect for that

**Comment by Radiicall** [comment]
Hi, I have now implemented a "Paused" feature. It will be in the next release, if you want to use it now then you can compile from source, you'll need to switch to a json file for the config though.

**Comment by tilda** [comment]
neat, thanks!
