### ISSUE TITLE
RPC not showing up on Discord

### ISSUE THREAD

**Issue by Fliegevieh** [Radiicall/jellyfin-rpc#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

My plan is to have the rpc running 24/7 on my Debian 12 machine. I installed the program via the python installer and it installed fine. I also activated autostart. Now the problem is (It might sounds dumb): I dont really know how to acces for example the terminal or even see if it's running. I know where the configuration file is but nothing more than that. Do I have to install something else?

Edit: On Windows it works just fine with the same configuration file.

Thanks for your help!

### Terminal output

/

### Jellyfin-RPC version

0.15.1

### What OS are you using?

Debian 12

### What version is the Jellyfin server on?

10.8.10

**Comment by 0xGingi** [comment]
For Linux, you need to use systemd

systemctl --user enable --now jellyfin-rpc <--- Starts Jellyfin-rpc and enables it on boot

systemctl --user status jellyfin-rpc <--- checks status

**Comment by Fliegevieh** [comment]
Is there any way I can have the rpc running on a headless server but have discord open on my PC?

**Comment by 0xGingi** [comment]
Kind of, but not very feasible, you could use https://github.com/OpenAsar/arrpc with a custom client, and for the bridge_mod.js when loading the rpc, change 127.0.0.1 to the ip of the server

**Comment by Radiicall** [comment]
> Thanks that helped!
> 
> Is there any way I can have the rpc running on a headless server but have discord open on my PC?

Apart from what @0xGingi said there's not much else you could try, If you find a solution for this please let me know.. Closing this issue for now
