### ISSUE TITLE
Stopped working after a day

### ISSUE THREAD

**Issue by 123321mario** [Radiicall/jellyfin-rpc#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

Basically I installed jellyfin-rpc on Monday morning, it worked absolutely fine the whole day then starting Tuesday it broke and doesn't show anything since. I tried reinstalling the service, using new bot client id, new api key, rebooting my server and PC but nope, even tried on another PC without success.

### Terminal output

Just wondering how to get logs when running as windows service ?

### Jellyfin-RPC version

0.15.3

### What OS are you using?

Windows 11

### What version is the Jellyfin server on?

4.8.0.58 (emby)

**Comment by Radiicall** [comment]
Press Windows + R and type in `%appdata%\jellyfin-rpc` you should find some log files there, also emby is only supported due to the jellyfin/emby api's being very similar, i dont have an emby server so if its emby specific then i dont know if i can help much

**Comment by 123321mario** [comment]
Thanks,
This is the error located in the log file:
```Images without Imgur requires port forwarding!
Failed to connect, retrying soon
Error: Couldn't connect to the Discord IPC socket
Failed to connect, retrying soon
Error: Couldn't connect to the Discord IPC socket
Failed to connect, retrying soon
Error: Couldn't connect to the Discord IPC socket
Failed to connect, retrying soon
Error: Couldn't connect to the Discord IPC socket
Failed to connect, retrying soon
Error: Couldn't connect to the Discord IPC socket
Failed to connect, retrying soon
Error: Couldn't connect to the Discord IPC socket
```
I retried reinstalling everything with new api key and client id again and for some reason it now works
I first tried on a jellyfin server then on my emby now both work fine
Closing for now
