### ISSUE TITLE
HTTPS with custom created certificates doesn't work

### ISSUE THREAD

**Issue by ProchyGaming** [Radiicall/jellyfin-rpc#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

When setting up jellyfin-rpc with a HTTPS URL that uses a self-made certificate, it doesn't work

### Terminal output

1: Error while getting content: Reqwest(
    reqwest::Error {
        kind: Request,
        url: Url {
            scheme: "https",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: Some(
                Domain(
                    "xxx",
                ),
            ),
            port: Some(
                8920,
            ),
            path: "/Sessions",
            query: Some(
                "api_key=xxx",
            ),
            fragment: None,
        },
        source: hyper::Error(
            Connect,
            Custom {
                kind: Other,
                error: Custom {
                    kind: InvalidData,
                    error: InvalidCertificate(
                        UnknownIssuer,
                    ),
                },
            },
        ),
    },
    "Is your Jellyfin URL set correctly?",
)

### Jellyfin-RPC version

0.15.4

### What OS are you using?

Windows 11

### What version is the Jellyfin server on?

10.8.11

**Comment by Radiicall** [comment]
I created a branch for this issue, ill see if i can fix it

**Comment by Radiicall** [comment]
Hey, can you try with the exe in this zip? 
[jellyfin-rpc.zip](https://github.com/Radiicall/jellyfin-rpc/files/13401369/jellyfin-rpc.zip)

If you don't want to run that exe then you can compile the branch https://github.com/Radiicall/jellyfin-rpc/tree/self-signed-certificate-error from source!

You also need to add some new lines to your config
```json
{
	"jellyfin": {
		"self_signed_cert": true, <-- This line needs to be added to the config
	},
}
```

**Comment by ProchyGaming** [comment]
Hey, thanks for the quick response! Your fixed worked, wonderful. Thank you a lot!

**Comment by ProchyGaming** [comment]
Okay so, it works better than before, how ever when i pause the playing video the status doesn't update on discord and the count-down for the duration of the episode keeps on going

**Comment by ProchyGaming** [comment]
> Okay so, it works better than before, however when i pause the video the status doesn't update on discord and the count-down for the duration of the episode keeps on going

To add to this, relaunching the video stops the status and it hasn't came back since. Even after removing the cert line and switching back to http, should i just create a new config and everything from scratch?

**Comment by Radiicall** [comment]
> Okay so, it works better than before, however when i pause the video the status doesn't update on discord and the count-down for the duration of the episode keeps on going

hmm thats interesting, I have only changed how it handles certificates, everything else should be as expected...

**Comment by Radiicall** [comment]
What client are you using?

**Comment by ProchyGaming** [comment]
> What client are you using?

I am using my own built official jellyfin client, it's basically the same as release just up to date with the jellyfin repo. However using the stable release of jellyfin-rpc with http works fine so I'm not sure what's the problem

**Comment by Radiicall** [comment]
My main computer runs linux so the compiled binary i sent you is a bit different from the one produced by github on releases and such, look at https://github.com/Radiicall/jellyfin-rpc/pull/86#issuecomment-1817672097, I updated the workflows in the repo so now artifacts from PRs will be uploaded, download the windows one from the page listed in that comment

**Comment by ProchyGaming** [comment]
I have downloaded the one in the artifacts, still same issue persists

**Comment by ProchyGaming** [comment]
Okay so i did some further testing, turns out the issue is not caused by jellyfin-rpc, it is something else but im not quite sure. Anyways thanks for fixing it, works properly now!
