### ISSUE TITLE
The file gets flagged as a virus by Windows Defender

### ISSUE THREAD

**Issue by SaltyMole** [Radiicall/jellyfin-rpc#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

"jellyfin-rpc.exe" is flagged as a virus.

VirusTotal link :
https://www.virustotal.com/gui/file/b33449a425d6d020813d9bb5700f0c888327ee1efa5edfa98c756a25b76af8e8/detection

### Jellyfin-RPC version

0.14.0

### What OS are you using?

Windows 11

### What version is the Jellyfin server on?

10.8.12

**Comment by Radiicall** [comment]
Update jellyfin-rpc and windows

**Comment by SaltyMole** [comment]
Windows is up-to-date, and so is Defender.
I just downloaded jellyfin-rpc using the python installer in the wiki, so I'm sure that I have the latest version.

**Comment by Radiicall** [comment]
> Windows is up-to-date, and so is Defender. I just downloaded jellyfin-rpc using the python installer in the wiki, so I'm sure that I have the latest version.

yeah okay, you typed 0.14.0 which is a whole major release behind so i thought you were out of date, ill submit the newest release to microsoft again so it'll be removed from their database (this has happened a few times now, usually have to resubmit it on every release)

**Comment by Radiicall** [comment]
Can you send what windows defender detects it as? Its probably something like "Bearfoos.B!ml"

**Comment by Radiicall** [comment]
> Can you send what windows defender detects it as? Its probably something like "Bearfoos.B!ml"

This cant be reported to Microsoft without knowing what defender is detecting it as..

**Comment by Summer-1999** [comment]
Hello, I installed this today and gets flagged by Windows Defender too.
It says:

> Detected: Trojan:Win32/Bearfoos.A!ml

Hope it helps

**Comment by Radiicall** [comment]
> Hello, I installed this today and gets flagged by Windows Defender too. It says:
> 
> > Detected: Trojan:Win32/Bearfoos.A!ml
> 
> Hope it helps

I submitted it but you probably just have to do the steps here to update your antivirus
https://www.microsoft.com/en-us/wdsi/defenderupdates
