### ISSUE TITLE
Support for multi-character separators

### ISSUE THREAD

**Issue by duckdotapk** [Radiicall/jellyfin-rpc#89]
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

The application crashes when trying to use a multi-character string as a separator.

I wanted to use "on" as a separator so it says "By Artist on Album".

### Describe the solution you'd like

I don't know Rust very much but I can see from a quick search of the code that the application is using a `char` for the separator. So maybe just change that? I'm not sure if that's easier said than done but just an observation.

**Comment by Radiicall** [comment]
You can find binaries for the test version at the bottom of [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7029944685) when the build is done

**Comment by Radiicall** [comment]
> You can find binaries for the test version at the bottom of [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7029944685) when the build is done

Please let me know if it works

**Comment by duckdotapk** [comment]
Seems to work great, thank you for the quick turnaround time :)
