### ISSUE TITLE
Error while getting content: Json(     Error("expected value", line: 1, column: 1), ) after install

### ISSUE THREAD

**Issue by szaszlyki21** [Radiicall/jellyfin-rpc#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

After install the program always throws out a "Error while getting content: Json(Error("expected value", line: 1, column: 1),)" no matter what mine json config file stores. I've tried it on Windows but it spits out the same error! I've also tried using the default config but with no results.

### Terminal output

jellyfin-rpc[778]: [771B blob data]
gru 10 13:31:46 user1 jellyfin-rpc[778]: 41: Error while getting content: Json(
gru 10 13:31:46 user1 jellyfin-rpc[778]:     Error("expected value", line: 1, column: 1),)

### Jellyfin-RPC version

0.15.5

### What OS are you using?

EndevourOS linux kernel6.6.4

### What version is the Jellyfin server on?

10.8.13

**Comment by Radiicall** [comment]
Can you send your config without the api_key or the imgur client id?

**Comment by szaszlyki21** [comment]
I've tried the config that was made on setup with the installer but now it looks like this just to be sure I didn't screw up anything else(main.json):
{
  "jellyfin": {
    "url": "https://example.com",
    "api_key": "apikey",
    "username": "username"
  }
}
of course with my info in it ;)

**Comment by Radiicall** [comment]
what client are you using? Does this happen if you try with just a browser for example?

**Comment by Radiicall** [comment]
It's most likely that the error is happening here [jellyfin.rs line 120-132](https://github.com/Radiicall/jellyfin-rpc/blob/main/jellyfin-rpc/src/services/jellyfin.rs#L120-L132). If you try visiting `YOUR_JF_URL/Sessions?api_key=YOUR_API_KEY` while watching something do you see anything here?

**Comment by szaszlyki21** [comment]
While playing music the link returns the song title, the artist and the album name - probably everything else as it is probably working correctly

**Comment by szaszlyki21** [comment]
> what client are you using? Does this happen if you try with just a browser for example?

I’ve tried using the official desktop client, the web client, Ampfin and Finamp

**Comment by Radiicall** [comment]
> While playing music the link returns the song title, the artist and the album name - probably everything else as it is probably working correctly

The code is expecting an array of values, so when you open the /Sessions browser page everything should be inside of a 0,1,2,3 etc object
![image](https://github.com/Radiicall/jellyfin-rpc/assets/66682497/6eae4dd4-740a-4b01-91e7-6eab62b7d1df)

**Comment by szaszlyki21** [comment]
any other idea why the app couldn't access the server? Maybe something with my reverse-proxy?

**Comment by Radiicall** [comment]
Add me on discord `radical.rs`

**Comment by Radiicall** [comment]
Problem with cosmos-cloud anti bot protection feature

**Comment by just5ky** [comment]
How was this fixed? @szaszlyki21 @Radiicall 
I'm seeing the same problem

**Comment by just5ky** [comment]
nvm, fixed it, made a typo after pasting the API key
