### ISSUE TITLE
Specific song not fetching/displaying correctly on Discord

### ISSUE THREAD

**Issue by AkikoKumagara** [Radiicall/jellyfin-rpc#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went wrong?

I'm playing the song "U" by DECO*27 from the album MANNEQUIN and the song info simply won't display within Discord even though it's working in the RPC program itself as far as I can tell.

This seems to only affect this song, nothing else on the album has this same issue as far as I've seen thus far.

The screenshot below shows what happens when I switch to it from the previous song while the previous song is still playing; basically, though, info simply isn't updated (the remaining duration from the previous track stays onscreen instead).

![image](https://github.com/Radiicall/jellyfin-rpc/assets/15231336/277682f7-754a-44af-8fc1-6b31c5d96b16)

The following is what is shown when the RPC application is loaded through Terminal, which looks correct to me.
![image](https://github.com/Radiicall/jellyfin-rpc/assets/15231336/59747151-31b7-46b1-9e08-7e88bd425bcd)

### Jellyfin-RPC version

0.15.5

### What OS are you using?

Windows 10

### What version is the Jellyfin server on?

10.8.13

**Comment by Radiicall** [comment]
hm discord might not support 1 character names, will have to test this later

**Comment by AkikoKumagara** [comment]
> hm discord might not support 1 character names, will have to test this later

Thanks, that was my theory, too.

**Comment by Radiicall** [comment]
The problem seems indeed to be with having a 1 character name, if anyone wants to take a look at this it should be a simple fix, there's already a length check in [jellyfin.rs](https://github.com/Radiicall/jellyfin-rpc/blob/main/jellyfin-rpc/src/services/jellyfin.rs#L170-L172). It just has to be adjusted to check for less than 1-2 characters, I didnt check if the minimum is 2 or 3.

**Comment by Radiicall** [comment]
Scroll all the way down on [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7487994096) and download the correct version for your system and check if that works.

**Comment by AkikoKumagara** [comment]
> Scroll all the way down on [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7487994096) and download the correct version for your system and check if that works.

Thanks! Here's what it looks like now.
![image](https://github.com/Radiicall/jellyfin-rpc/assets/15231336/ce133546-6ca7-41c3-b371-c0368635c384)

**Comment by Radiicall** [comment]
> > Scroll all the way down on [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7487994096) and download the correct version for your system and check if that works.
> 
> Thanks! Here's what it looks like now. 
> ![image](https://private-user-images.githubusercontent.com/15231336/296070792-ce133546-6ca7-41c3-b371-c0368635c384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTM1NTQsIm5iZiI6MTcwNTA1MzI1NCwicGF0aCI6Ii8xNTIzMTMzNi8yOTYwNzA3OTItY2UxMzM1NDYtNmNhNy00MWMzLWIzNzEtYzAzNjg2MzVjMzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA5NTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYjA0ZTBmOGIyMjBiMThiYWIwMGEyNDhhZjk2NDNhMGNkMTNmNGViMWRjYjhlYWY1MDkwOTQ1MTg0NDVjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qc-WaFHN0nrA8f9oHoL1MfX9q6ukgb2kbt131DBaFYM)

Might actually be better to move the by line to the same one as the song name hmm, this will require some refactoring though.. I'll look into it when i have time

**Comment by Radiicall** [comment]
> Instead of adding "- Jellyfin" or some other filler text, maybe you could add some blank space following the short text so that everything is still cohesive and uniform. I'm not sure if that's possible, but I think it'd look better if so. Just a thought.

I'll check if It's possible, I'm not sure if it will work properly on all clients though + discord might just count it as nothing and then not display like before

**Comment by Radiicall** [comment]
> Scroll all the way down on [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7487994096) and download the correct version for your system and check if that works.

Try [this one](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7900558969)

**Comment by AkikoKumagara** [comment]
> > Scroll all the way down on [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7487994096) and download the correct version for your system and check if that works.
> 
> Try [this one](https://github.com/Radiicall/jellyfin-rpc/actions/runs/7900558969)

Perfect! This is great.

![image](https://github.com/Radiicall/jellyfin-rpc/assets/15231336/e3450f18-b459-4f52-8f39-cfdd0c3b4abc)

**Comment by Radiicall** [comment]
Fixed in 1.0.0

**Comment by AkikoKumagara** [comment]
Thanks a bunch for accommodating me and coming up with a good solution. I appreciate it!
